server:
  port: 8080
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  config: classpath:log4j2.xml
  level:
    com.huawei.*: debug
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db1?serverTimezone=GMT%2B8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver