server:
  port: 8081
graphiql:
  enabled: true
  mapping: /graphiql
  endpoint:
    graphql: /graphql
logging:
  config: classpath:logback-spring.xml
  level:
    com.huawei.*: debug
mybatis:
  mapper-locations: classpath:mapper/*.xml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db1?serverTimezone=GMT%2B8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev